[package]
name = "gzip"
version = "0.1.1"
authors = ["Jude Peel <judepeel.dev@gmail.com>"]
repository = "https://github.com/jude-peel/gzip/"
readme = "README.md"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
